---
- name: Create group
  group:
    name: "{{ gophernicus_group }}"
    state: present

- name: Create User
  user:
    name: "{{ gophernicus_user }}"
    state: present
    shell: /sbin/nologin
    group: "{{ gophernicus_group }}"

- name: Install Gophernicus
  ansible.builtin.package:
    name: gophernicus
    state: present
  when: ansible_os_family == "Debian"

- name: Download file with check (sha256)
  get_url:
    url: "https://github.com/gophernicus/gophernicus/releases/download/{{ gophernicus_version }}/gophernicus-{{ gophernicus_version }}-x86_64-static"
    dest: /usr/local/bin/gophernicus
    checksum: "sha256:{{ gophernicus_sha256 }}"
  when: ansible_os_family != "Debian"

- name: Systemd service
  ansible.builtin.template:
    dest: /etc/systemd/system/gophernicus@.service
    src: gophernicus.service
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Systemd socket
  ansible.builtin.template:
    dest: /etc/systemd/system/gophernicus.socket
    src: gophernicus.socket
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: create override folder for gophernicus@.service
  ansible.builtin.file:
    path: /etc/systemd/system/gophernicus@.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Install systemd overrides
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/gophernicus@.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
- name: Gophernicus defaults
  ansible.builtin.template:
    src: gophernicus.default
    dest: /etc/default/gophernicus
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
- name: Gophernicus Content Directory
  ansible.builtin.file:
    path: "{{ gopher_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Gophernicus Content Directories
  ansible.builtin.file:
    path: "{{ gopher_data_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ gopher_hosts }}"
- name: Start Gophernicus socket
  ansible.builtin.systemd:
    name: gophernicus.socket
    enabled: true
    state: started